on:
  pull_request:
  push:
    branches:
      - master

name: Build
jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
         - name: Log the node version
           run: |
             node -v
             cat /etc/os-release
             pwd
