on:
  pull_request:
  push:
    branches:
      - master

name: Build
jobs:
  unit_test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Check helm unittest
        run: |
          helm version
