on:
  pull_request:
  push:
    branches:
      - master

name: Build
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      HELM_PLUGINS: /home/runner/.cache/helm/plugins
    steps:
      - name: upgrade helm
        run: sudo snap install --classic helm 

      - name: download helm unittest
        run: wget https://github.com/quintush/helm-unittest/releases/download/v0.2.6/helm-unittest-linux-amd64-0.2.6.tgz

      - name: upgrade helm
        run: mkdir -p $HOME/.cache/helm/plugins/https-github.com-quintush-helm-unittest

      - name: extract helm unittest
        run: tar -zxvf helm-unittest-linux-amd64-0.2.6.tgz -C $HOME/.cache/helm/plugins/https-github.com-quintush-helm-unittest

      - name: list helm plugins
        run: helm plugin list

      - name: git-checkout
        uses: actions/checkout@v1

      - name: run helm unittests 
        run: helm unittest -3 -v charts/microservice/ci/microservice-values-new-ingress.yaml charts/microservice/

