on:
  pull_request:
  push:
    branches:
      - master

name: Build
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: upgrade helm
        run: sudo snap install helm

      - name: install git
        run: sudo apt-get install git

      - name: install helm unittest plugin
        run:  helm install plugin https://github.com/quintush/helm-unittest

      - name: git-checkout
        uses: actions/checkout@v1

        

